# Directory to parse
source: ./dev/hologram

# Directory to build the styleguide
destination: ./release/wedding/styleguide

# Hologram theme
# documentation_assets: ./bower_components/Cortana
# custom_markdown: ./bower_components/Cortana/CortanaMarkdownRenderer.rb
documentation_assets: ./dev/hologram/templates
custom_markdown: ./dev/hologram/templates/markdown_renderer.rb

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - '//fonts.googleapis.com/css?family=Open+Sans%7CLibre+Baskerville'
  - '../assets/css/common.css'
  - '../assets/css/kumamoto/style.css'
  - '../assets/css/styleguide.css'

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - '//code.jquery.com/jquery-1.10.2.min.js'
  - '//fonts.googleapis.com/css?family=Open+Sans%7CLibre+Baskerville'
  - '../assets/js/lib.js'
  - '../assets/js/common.js'

styleguide_name: 'MPQ Document'
